apiVersion: apps/v1
kind: Deployment

metadata:
  name: backstage
  namespace: backstage
  labels:
    app: aram-k8s-service # <--- Matches the label-selector in catalog-info.yaml
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backstage

  template:
    metadata:
      labels:
        app: backstage

    spec:
      containers:
        - name: backstage
          image: ${FULL_IMAGE_TAG}
          ports:
            - containerPort: 7007